name: Build and Publish Linux Wheels

# This workflow is for PRODUCTION RELEASES only
# For performance monitoring and flamegraphs, see .github/workflows/benchmarks.yml

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
    - name: Create virtual environment
      run: uv venv
      
    - name: Install maturin
      run: uv pip install maturin[patchelf]
      
    - name: Run Rust tests
      run: cargo test --verbose
      
    - name: Install Python dependencies and run Python tests
      run: |
        # Install Python dependencies needed for testing
        uv pip install pytest pandas pyarrow
        
        # Build the Python module for testing (development mode)
        uv run maturin develop
        
        # Run Python tests
        uv run python -m pytest tests/test_bitemporal.py -v
        
    - name: Build release binary (smoke test)
      run: |
        # Build release binary to ensure it compiles correctly
        # This catches any release-specific compilation issues
        cargo build --release

  build-linux-wheels:
    needs: test  # Only run if tests pass
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
        python-version: ['3.9', '3.10', '3.11', '3.12']
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"
        else
          echo "VERSION=0.1.0-dev" >> $GITHUB_OUTPUT
          echo "Building development version"
        fi
        
    - name: Update version in files
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=${{ steps.version.outputs.VERSION }}
        echo "Updating version to: $VERSION"
        
        # Update Cargo.toml
        sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
        
        # Update pyproject.toml
        sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
        
        # Verify changes
        echo "Updated Cargo.toml:"
        grep "^version" Cargo.toml
        echo "Updated pyproject.toml:"
        grep "^version" pyproject.toml
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}-unknown-linux-gnu
        
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
    - name: Create virtual environment
      run: uv venv
      
    - name: Install maturin
      run: uv pip install maturin[patchelf]
      
    - name: Build wheel
      run: |
        # Use the specific Python version set up by actions/setup-python
        PYTHON_PATH=$(which python3)
        echo "Using Python interpreter: $PYTHON_PATH (${{ matrix.python-version }})"
        python3 --version
        
        # Build wheel for this specific Python version
        uv run maturin build --release --out dist --interpreter $PYTHON_PATH
        
    - name: List built wheels
      run: ls -la dist/
      
    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-${{ matrix.target }}-py${{ matrix.python-version }}
        path: dist/*.whl
        
  publish-to-gitea:
    needs: build-linux-wheels
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Only publish on version tags
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all wheel artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist-all/
        
    - name: Flatten wheel directory
      run: |
        mkdir -p dist/
        find dist-all/ -name "*.whl" -exec cp {} dist/ \;
        ls -la dist/
        
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install twine
      run: pip install twine
      
    - name: Configure package index
      run: |
        cat > ~/.pypirc << EOF
        [distutils]
        index-servers = gitea
        
        [gitea]
        repository = ${{ secrets.GITEA_PACKAGE_URL }}/simple/
        username = ${{ secrets.GITEA_USERNAME }}
        password = ${{ secrets.GITEA_TOKEN }}
        EOF
        
    - name: Publish to Gitea Package Registry
      run: |
        twine upload --repository gitea dist/*.whl
        
    - name: Create release notes
      run: |
        cat > release_notes.md << EOF
        # Release ${{ steps.version.outputs.VERSION }}
        
        ## Linux Wheels Built
        - x86_64 (Intel/AMD 64-bit) for Python 3.9, 3.10, 3.11, 3.12
        
        ## Installation
        \`\`\`bash
        # Install from Gitea package registry
        pip install --index-url ${{ secrets.GITEA_PACKAGE_URL }}/simple/ pytemporal==${{ steps.version.outputs.VERSION }}
        \`\`\`
        
        ## Features
        - High-performance bitemporal timeseries processing
        - Microsecond precision timestamps for audit trails
        - Conflation optimization for reduced storage
        - Adaptive parallelization for large datasets
        EOF
        
    - name: Create Gitea Release
      uses: actions/gitea-release@v1
      with:
        gitea_url: ${{ github.server_url }}
        token: ${{ secrets.GITEA_TOKEN }}
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body_path: release_notes.md
        files: dist/*.whl