blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://gingermike.github.io/pytemporal/
    about: Check the documentation for API reference, examples, and performance guides
  - name: 💬 GitHub Discussions
    url: https://github.com/gingermike/pytemporal/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/gingermike/pytemporal/security/advisories/new
    about: Report security vulnerabilities privately